INSERT INTO products (name, price, production_duration, description)
VALUES 
    ('Premium Smartphone', 599.99, 2, 'High-end smartphone with cutting-edge features.'),
    ('Laptop Computer', 999.99, 3, 'Powerful laptop for professional and personal use.'),
    ('Wireless Headphones', 149.99, 1, 'Sleek and comfortable headphones for immersive audio experience.'),
    ('Smart Watch', 249.99, 2, 'Fitness tracker and smartwatch with advanced health monitoring features.'),
    ('Digital Camera', 399.99, 4, 'Professional-grade camera for capturing stunning photos and videos.'),
    ('Tablet Computer', 349.99, 2, 'Portable device for entertainment and productivity on-the-go.'),
    ('Gaming Console', 449.99, 3, 'Next-generation gaming console for immersive gaming experiences.'),
    ('Smart Speaker', 129.99, 1, 'Voice-controlled speaker with smart home integration.'),
    ('Wireless Router', 79.99, 1, 'High-speed wireless router for seamless internet connectivity.'),
    ('Fitness Tracker', 79.99, 1, 'Track your activity, exercise, sleep, and more with this fitness tracker.'),
    ('Bluetooth Earbuds', 99.99, 1, 'Wireless earbuds with long battery life and clear sound quality.'),
    ('External Hard Drive', 119.99, 1, 'Expand your storage capacity with this reliable external hard drive.'),
    ('Coffee Maker', 59.99, 1, 'Start your day with a perfect cup of coffee from this programmable coffee maker.'),
    ('Air Purifier', 199.99, 1, 'Keep the air in your home clean and fresh with this efficient air purifier.'),
    ('Electric Toothbrush', 39.99, 1, 'Improve your oral health with this advanced electric toothbrush.'),
    ('Robot Vacuum Cleaner', 299.99, 1, 'Effortlessly clean your floors with this smart robot vacuum cleaner.'),
    ('Portable Power Bank', 29.99, 1, 'Stay charged on-the-go with this compact and lightweight power bank.'),
    ('Wireless Charging Pad', 39.99, 1, 'Conveniently charge your devices wirelessly with this charging pad.'),
    ('LED Desk Lamp', 49.99, 1, 'Illuminate your workspace with this energy-efficient LED desk lamp.'),
    ('Smart Thermostat', 149.99, 1, 'Control your homes temperature from anywhere with this smart thermostat.'),
    ('Electric Kettle', 29.99, 1, 'Boil water quickly and efficiently with this electric kettle.'),
    ('Bluetooth Speaker', 79.99, 1, 'Enjoy your favorite music wirelessly with this portable Bluetooth speaker.'),
    ('Noise Cancelling Headphones', 199.99, 1, 'Immerse yourself in music without distractions with these noise cancelling headphones.'),
    ('Digital Picture Frame', 99.99, 1, 'Display your favorite memories with this digital picture frame.'),
    ('Smart Doorbell', 199.99, 1, 'Enhance your home security with this smart video doorbell.'),
    ('Action Camera', 199.99, 1, 'Capture your adventures in stunning detail with this action camera.'),
    ('Wireless Security Camera', 149.99, 1, 'Keep an eye on your home with this wireless security camera.'),
    ('Smart Lock', 149.99, 1, 'Secure your home with this keyless smart lock.'),
    ('Compact Refrigerator', 199.99, 1, 'Keep your drinks and snacks cool with this compact refrigerator.'),
    ('Blender', 39.99, 1, 'Create delicious smoothies and shakes with this powerful blender.'),
    ('Air Fryer', 79.99, 1, 'Cook your favorite foods with little to no oil using this air fryer.'),
    ('Rice Cooker', 29.99, 1, 'Cook perfect rice every time with this easy-to-use rice cooker.'),
    ('Portable Bluetooth Printer', 99.99, 1, 'Print photos and documents on-the-go with this portable Bluetooth printer.'),
    ('Wireless Mouse', 29.99, 1, 'Navigate your computer with ease using this wireless mouse.'),
    ('Compact Digital Scale', 19.99, 1, 'Accurately measure ingredients with this compact digital scale.'),
    ('Stainless Steel Water Bottle', 19.99, 1, 'Stay hydrated on-the-go with this durable stainless steel water bottle.'),
    ('Travel Pillow', 14.99, 1, 'Rest comfortably during your travels with this ergonomic travel pillow.'),
    ('UV Sterilizer', 49.99, 1, 'Sanitize your belongings quickly and effectively with this UV sterilizer.'),
    ('Car Dash Cam', 79.99, 1, 'Record your drives for safety and security with this car dash cam.'),
    ('Foldable Laptop Stand', 29.99, 1, 'Elevate your laptop for ergonomic typing and viewing with this foldable stand.'),
    ('Cordless Handheld Vacuum', 79.99, 1, 'Clean up messes quickly and easily with this cordless handheld vacuum.'),
    ('Wireless Charging Stand', 49.99, 1, 'Charge your phone wirelessly while keeping it upright with this charging stand.'),
    ('Solar Power Bank', 39.99, 1, 'Charge your devices using renewable energy with this solar power bank.'),
    ('Memory Foam Mattress Topper', 99.99, 1, 'Upgrade your mattress for added comfort and support with this memory foam topper.'),
    ('Smart Plug', 19.99, 1, 'Control your devices remotely with this WiFi-enabled smart plug.'),
    ('Electric Wine Opener', 29.99, 1, 'Open wine bottles effortlessly with this electric wine opener.'),
    ('Handheld Milk Frother', 19.99, 1, 'Froth milk for lattes and cappuccinos at home with this handheld frother.'),
    ('Grill Thermometer', 19.99, 1, 'Monitor the temperature of your grill for perfect cooking results with this thermometer.'),
    ('Adjustable Laptop Stand', 39.99, 1, 'Customize the height and angle of your laptop for comfortable use with this adjustable stand.'),
    ('Wireless Charging Car Mount', 49.99, 1, 'Charge your phone while driving with this wireless charging car mount.'),
    ('Fitness Exercise Ball', 19.99, 1, 'Improve your balance, stability, and core strength with this fitness exercise ball.'),
    ('Digital Alarm Clock', 14.99, 1, 'Wake up on time with this easy-to-use digital alarm clock.'),
    ('Collapsible Water Bottle', 9.99, 1, 'Stay hydrated on-the-go with this collapsible water bottle.'),
    ('LED Flashlight', 9.99, 1, 'Illuminate your path with this compact and bright LED flashlight.'),
    ('Mini Portable Fan', 14.99, 1, 'Stay cool wherever you go with this mini portable fan.'),
    ('Desktop Organizer', 24.99, 1, 'Keep your desk neat and organized with this desktop organizer.'),
    ('Reusable Shopping Bags', 14.99, 1, 'Reduce waste and carry groceries with ease using these reusable shopping bags.'),
    ('Foldable Umbrella', 9.99, 1, 'Stay dry on rainy days with this compact and lightweight foldable umbrella.'),
    ('Ceramic Mug Set', 19.99, 1, 'Enjoy your favorite beverages in style with this ceramic mug set.'),
    ('Bluetooth Car Adapter', 24.99, 1, 'Stream music and take calls hands-free in your car with this Bluetooth adapter.'),
    ('Portable Clothes Steamer', 29.99, 1, 'Remove wrinkles from clothing quickly and easily with this portable clothes steamer.'),
    ('Mini Projector', 99.99, 1, 'Transform any space into a home theater with this compact mini projector.'),
    ('Wireless Earbuds Case', 9.99, 1, 'Protect and charge your wireless earbuds with this convenient case.'),
    ('Kitchen Timer', 9.99, 1, 'Keep track of cooking times with this easy-to-use kitchen timer.'),
    ('Vegetable Spiralizer', 14.99, 1, 'Create healthy vegetable noodles and ribbons with this spiralizer.'),
    ('Resistance Bands Set', 29.99, 1, 'Work out anywhere with this set of resistance bands for strength training.'),
    ('Reusable Silicone Food Bags', 19.99, 1, 'Reduce plastic waste with these reusable silicone food storage bags.'),
    ('Compact Binoculars', 29.99, 1, 'Explore the outdoors and enjoy sporting events with these compact binoculars.'),
    ('Stainless Steel Travel Mug', 14.99, 1, 'Keep your beverages hot or cold on-the-go with this stainless steel travel mug.'),
    ('Phone Stand', 9.99, 1, 'View your phone hands-free in portrait or landscape mode with this versatile phone stand.');

UPDATE products
SET storage_amount = FLOOR(RAND() * 101);